/**
 * python-slice.ts — function-slice extraction for Python behaviour-equivalence on REAL files.
 *
 * The Python differential engine (`python-equiv.ts`) loads a module with
 * `importlib.util.spec_from_file_location` and executes it. A real dependency-laden file —
 * e.g. `requests/utils.py` with `from .compat import urlparse`, `from urllib3.util import …`,
 * and module-level constants — fails to load (relative import with no parent package, or a
 * third-party dep absent in the sandbox). The engine then honestly degrades to `unverified`.
 *
 * This module bridges that gap by running an AST-based slice extractor (in Python, where the
 * semantics belong) that pulls the TARGET function PLUS the transitive closure of the
 * module-level names it actually references into one self-contained module. Imports are
 * handled per an HONEST rule set:
 *
 *   (a) module-level CONSTANTS / helper functions / classes the target uses → inlined.
 *   (b) `from .sibling import name` (relative) where `name` resolves in the sibling file to a
 *       stdlib re-export or a trivial binding (`builtin_str = str`)               → resolved &
 *       inlined / rewritten to the underlying stdlib import.                          inlined.
 *   (c) stdlib `import`/`from` the slice actually uses (re, struct, math, …)      → kept.
 *   (d) an import the slice uses that is THIRD-PARTY (urllib3, werkzeug, …) or a  → DECLINE with
 *       relative name that cannot be resolved to stdlib/constant                     a reason; the
 *                                                                                     caller emits
 *                                                                                     `unverified`.
 *
 * The purity gate in the engine still runs on the SLICE, so a target whose own body calls
 * `socket.inet_aton` / `os.environ` is correctly declined as impure (real network/IO), not
 * fabricated as a pass.
 *
 * Implementation: shells out to a generated, self-contained Python AST script (stdlib only),
 * mirroring the engine's subprocess design. Never throws — every failure becomes
 * `{ ok: false, reason }`.
 */

import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

export type PySliceResult =
  | { readonly ok: true; readonly source: string; readonly inlined: readonly string[] }
  | { readonly ok: false; readonly reason: string };

/** The slice extractor script. stdlib-only; emits a JSON object on stdout. */
const SLICE_SCRIPT = String.raw`# AUTOGENERATED by python-slice.ts — AST function-slice extractor. Do not edit by hand.
import ast
import json
import os
import sys


# stdlib top-level module names we are willing to keep as imports in the slice (deterministic,
# sandbox-available pure transforms / math). NOT a guarantee of purity — the engine's purity
# gate still runs on the slice and will decline socket/os/io/etc. used in the target body.
_STDLIB_KEEP = {
    "re", "struct", "math", "json", "itertools", "functools", "collections",
    "string", "decimal", "fractions", "bisect", "heapq", "operator", "copy",
    "datetime", "calendar", "urllib", "html", "base64", "binascii", "hashlib",
    "textwrap", "unicodedata", "enum", "types", "typing", "abc", "numbers",
}

# Third-party / un-isolatable top-level modules — if the slice genuinely uses one, decline.
def _is_relative(node):
    return isinstance(node, ast.ImportFrom) and (node.level or 0) > 0


def _module_defs(tree):
    """Map name -> (kind, node) for top-level defs/classes/assignments."""
    defs = {}
    for n in tree.body:
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
            defs[n.name] = ("func", n)
        elif isinstance(n, ast.ClassDef):
            defs[n.name] = ("class", n)
        elif isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Name):
                    defs[t.id] = ("assign", n)
        elif isinstance(n, ast.AnnAssign) and isinstance(n.target, ast.Name) and n.value is not None:
            defs[n.target.id] = ("annassign", n)
    return defs


def _import_bindings(tree):
    """Map local-name -> (node, kind, info) for every import binding at module level."""
    binds = {}
    for n in tree.body:
        if isinstance(n, ast.Import):
            for a in n.names:
                local = (a.asname or a.name).split(".")[0]
                binds[local] = (n, "import", a.name)
        elif isinstance(n, ast.ImportFrom):
            mod = n.module or ""
            level = n.level or 0
            for a in n.names:
                local = a.asname or a.name
                binds[local] = (n, "importfrom", (mod, level, a.name))
    return binds


def _bound_names_of_function(fn):
    """Names locally bound inside a function: its params, assignments, for/with/comprehension
    targets, nested def/class names, except-as, and walrus targets. Used so we only treat
    genuinely-FREE names (loaded but not bound) as dependencies to resolve."""
    bound = set()
    a = fn.args
    for p in (a.posonlyargs + a.args + a.kwonlyargs):
        bound.add(p.arg)
    if a.vararg:
        bound.add(a.vararg.arg)
    if a.kwarg:
        bound.add(a.kwarg.arg)

    for nd in ast.walk(fn):
        if isinstance(nd, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if nd is not fn:
                bound.add(nd.name)
        elif isinstance(nd, ast.Assign):
            for t in nd.targets:
                for sub in ast.walk(t):
                    if isinstance(sub, ast.Name):
                        bound.add(sub.id)
        elif isinstance(nd, (ast.AnnAssign, ast.AugAssign)):
            for sub in ast.walk(nd.target):
                if isinstance(sub, ast.Name):
                    bound.add(sub.id)
        elif isinstance(nd, ast.NamedExpr) and isinstance(nd.target, ast.Name):
            bound.add(nd.target.id)
        elif isinstance(nd, (ast.For, ast.AsyncFor)):
            for sub in ast.walk(nd.target):
                if isinstance(sub, ast.Name):
                    bound.add(sub.id)
        elif isinstance(nd, ast.comprehension):
            for sub in ast.walk(nd.target):
                if isinstance(sub, ast.Name):
                    bound.add(sub.id)
        elif isinstance(nd, ast.withitem) and nd.optional_vars is not None:
            for sub in ast.walk(nd.optional_vars):
                if isinstance(sub, ast.Name):
                    bound.add(sub.id)
        elif isinstance(nd, ast.ExceptHandler) and nd.name:
            bound.add(nd.name)
        elif isinstance(nd, (ast.Import, ast.ImportFrom)):
            for al in nd.names:
                bound.add((al.asname or al.name).split(".")[0])
        elif isinstance(nd, ast.Lambda):
            la = nd.args
            for p in (la.posonlyargs + la.args + la.kwonlyargs):
                bound.add(p.arg)
            if la.vararg:
                bound.add(la.vararg.arg)
            if la.kwarg:
                bound.add(la.kwarg.arg)
    return bound


def _loaded_names(node):
    """Identifiers LOADED in a node (excludes attribute member names and pure stores)."""
    names = set()

    class V(ast.NodeVisitor):
        def visit_Name(self, nd):
            if isinstance(nd.ctx, ast.Load):
                names.add(nd.id)

        def visit_Attribute(self, nd):
            self.visit(nd.value)

    V().visit(node)
    return names


def _free_names(node):
    """Genuinely-free identifiers of a def/class node: names loaded but not locally bound.
    For non-function nodes (e.g. a module-level assignment), returns all loaded names."""
    loaded = _loaded_names(node)
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return loaded - _bound_names_of_function(node)
    return loaded


_BUILTINS = set(dir(__builtins__)) if isinstance(__builtins__, dict) is False else set(__builtins__.keys())
_BUILTINS |= {"True", "False", "None"}
# NOTE: dunders like __version__ are NOT builtins — they are module-level names (often from a
# relative import) and MUST be resolved/inlined, never silently dropped (a dropped free name
# would NameError at runtime and fabricate a false divergence).


def _resolve_relative_file(base_file, level, module):
    """Resolve a relative import 'from (level dots)module import ...' to a sibling .py path."""
    d = os.path.dirname(os.path.abspath(base_file))
    for _ in range(level - 1):
        d = os.path.dirname(d)
    if module:
        parts = module.split(".")
        cand = os.path.join(d, *parts) + ".py"
        if os.path.isfile(cand):
            return cand
        pkg = os.path.join(d, *parts, "__init__.py")
        if os.path.isfile(pkg):
            return pkg
    return None


def _find_binding_in_sibling(sib_path, name, depth=0):
    """In a sibling module, find how the imported name is bound. Returns a dict describing how to inline it:
        {"kind": "assign", "src": "<source text>"}      simple module-level binding (e.g. builtin_str = str)
        {"kind": "stdlib", "import": "<import stmt>"}   re-exported from a stdlib module
        {"kind": "func", "src": "<source>"}            a pure function/class def
        None                                            unresolvable / third-party
    """
    if depth > 4:
        return None
    try:
        src = open(sib_path, encoding="utf-8").read()
        tree = ast.parse(src)
    except Exception:
        return None
    lines = src.splitlines()

    # direct assignment: name = <expr>
    for n in tree.body:
        if isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Name) and t.id == name:
                    seg = ast.get_source_segment(src, n)
                    if seg is not None:
                        return {"kind": "assign", "src": seg}
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) and n.name == name:
            seg = ast.get_source_segment(src, n)
            if seg is not None:
                return {"kind": "func", "src": seg}

    # import binding: from <mod> import name  /  import mod as name
    for n in tree.body:
        if isinstance(n, ast.ImportFrom):
            mod = n.module or ""
            level = n.level or 0
            for a in n.names:
                local = a.asname or a.name
                if local != name:
                    continue
                top = mod.split(".")[0]
                if level == 0 and top in _STDLIB_KEEP:
                    # re-export from stdlib: keep an equivalent import (use original name)
                    asname = (" as %s" % name) if a.asname or (a.name != name) else ""
                    return {"kind": "stdlib", "import": "from %s import %s%s" % (mod, a.name, asname)}
                if level > 0:
                    # chase one more level of relative re-export
                    nxt = _resolve_relative_file(sib_path, level, mod)
                    if nxt:
                        r = _find_binding_in_sibling(nxt, a.name, depth + 1)
                        if r:
                            if r.get("kind") in ("assign", "func") and a.asname and a.name != name:
                                pass
                            return r
                # third-party / unresolved
                return None
        if isinstance(n, ast.Import):
            for a in n.names:
                local = (a.asname or a.name).split(".")[0]
                if local == name:
                    top = a.name.split(".")[0]
                    if top in _STDLIB_KEEP:
                        asname = (" as %s" % name) if a.asname else ""
                        return {"kind": "stdlib", "import": "import %s%s" % (a.name, asname)}
                    return None
    return None


def main():
    job = json.load(open(sys.argv[1], encoding="utf-8"))
    src_path = job["sourceFile"]   # may be "" when unknown
    code = job["source"]
    target = job["target"]

    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        print(json.dumps({"ok": False, "reason": "could not parse source: %s" % e}))
        return

    defs = _module_defs(tree)
    imports = _import_bindings(tree)

    if target not in defs or defs[target][0] not in ("func",):
        # maybe the target is an alias (f = before); not expected for real files. Decline.
        print(json.dumps({"ok": False, "reason": "target function %r not found at module level" % target}))
        return

    emitted = []          # ordered (name) list, deps first
    emitted_src = {}       # name -> source text to emit
    stdlib_imports = []    # ["import re", ...]
    inlined = []           # provenance
    unresolved = set()     # genuinely-free names we could not resolve → decline if non-empty
    seen = set()
    worklist = [target]

    while worklist:
        name = worklist.pop()
        if name in seen:
            continue
        seen.add(name)

        if name in defs:
            kind, node = defs[name]
            seg = ast.get_source_segment(code, node)
            if seg is None:
                print(json.dumps({"ok": False, "reason": "could not extract source for %r" % name}))
                return
            emitted_src[name] = seg
            emitted.append(name)
            # queue this decl's free refs
            for ref in _free_names(node):
                if ref in _BUILTINS or ref == name:
                    continue
                worklist.append(ref)
            continue

        if name in imports:
            inode, ikind, info = imports[name]
            if ikind == "import":
                top = info.split(".")[0]
                if top in _STDLIB_KEEP:
                    stmt = ast.get_source_segment(code, inode) or ("import %s" % info)
                    # keep only the single relevant alias to avoid pulling siblings
                    stdlib_imports.append("import %s%s" % (info, ""))
                    continue
                print(json.dumps({"ok": False,
                                  "reason": "target depends on external module '%s' which cannot be isolated in the sandbox" % info}))
                return
            else:  # importfrom
                mod, level, orig = info
                top = mod.split(".")[0]
                if level == 0 and top in _STDLIB_KEEP:
                    asname = (" as %s" % name) if name != orig else ""
                    stdlib_imports.append("from %s import %s%s" % (mod, orig, asname))
                    continue
                if level == 0:
                    print(json.dumps({"ok": False,
                                      "reason": "target depends on external module '%s' (name '%s') which cannot be isolated" % (mod, name)}))
                    return
                # relative import: resolve in sibling file
                if not src_path:
                    print(json.dumps({"ok": False,
                                      "reason": "relative import 'from %s%s import %s' cannot be resolved (source path unknown)" % ("." * level, mod, orig)}))
                    return
                sib = _resolve_relative_file(src_path, level, mod)
                if not sib:
                    print(json.dumps({"ok": False,
                                      "reason": "relative import 'from %s%s import %s' could not be resolved on disk" % ("." * level, mod, orig)}))
                    return
                res = _find_binding_in_sibling(sib, orig)
                if res is None:
                    print(json.dumps({"ok": False,
                                      "reason": "relative import 'from %s%s import %s' resolves to a third-party / un-isolatable binding" % ("." * level, mod, orig)}))
                    return
                if res["kind"] == "stdlib":
                    imp = res["import"]
                    # rewrite to the LOCAL name if it differs
                    if name != orig and (" as " not in imp):
                        imp = imp + (" as %s" % name)
                    stdlib_imports.append(imp)
                    inlined.append("%s ← %s%s (stdlib re-export)" % (name, "." * level, mod))
                elif res["kind"] in ("assign", "func"):
                    seg = res["src"]
                    # If the binding name differs from the local alias, add an alias.
                    emitted_src[name] = seg
                    emitted.append(name)
                    inlined.append("%s ← %s%s" % (name, "." * level, mod))
                    # queue the FREE refs of the inlined binding (it may use stdlib names or
                    # further siblings). Using free-name analysis avoids re-queuing the
                    # binding's own params/locals as phantom dependencies.
                    try:
                        sub = ast.parse(seg)
                        for snode in sub.body:
                            for ref in _free_names(snode):
                                if ref not in _BUILTINS and ref != name:
                                    worklist.append(ref)
                    except Exception:
                        pass
                continue

        # name is neither a module-level def nor an import binding. Since _free_names already
        # excluded params/locals/comprehension vars, a name that reaches here is a GENUINELY
        # UNRESOLVED free reference (e.g. a module-level name the file never defines, or a
        # name from a star-import we cannot model). Record it; an unresolved reference means
        # the slice would NameError at runtime, so we decline honestly rather than emit a
        # broken slice that fabricates a false divergence.
        if name not in _BUILTINS:
            unresolved.add(name)

    # HONESTY GUARD: if any genuinely-free name could not be resolved, the slice would
    # NameError at runtime — emitting it would fabricate a false divergence. Decline instead.
    unresolved = {u for u in unresolved if u not in emitted_src and u not in _BUILTINS}
    if unresolved:
        print(json.dumps({"ok": False,
                          "reason": "slice incomplete: unresolved free name(s) %s — cannot isolate without fabricating behaviour" % ", ".join(sorted(unresolved))}))
        return

    # Assemble: stdlib imports (dedup, order-stable), then deps in dependency order (reverse of
    # emission since we appended deps after their referrer — re-order: emit leaves first).
    seen_imp = []
    for i in stdlib_imports:
        if i not in seen_imp:
            seen_imp.append(i)

    # emitted currently has referrer-before-dep order; reverse so dependencies precede users.
    ordered = []
    for nm in reversed(emitted):
        if nm in emitted_src and nm not in ordered:
            ordered.append(nm)

    parts = []
    parts.extend(seen_imp)
    if seen_imp:
        parts.append("")
    for nm in ordered:
        parts.append(emitted_src[nm])
        parts.append("")

    out = "\n".join(parts).rstrip() + "\n"
    print(json.dumps({"ok": True, "source": out, "inlined": inlined}))


if __name__ == "__main__":
    main()
`;

function resolvePython(): string {
  const override = (process.env.HEALTHY_AI_PYTHON ?? '').trim();
  if (override) return override;
  return process.platform === 'win32' ? 'python' : 'python3';
}

/**
 * Build a self-contained Python module exporting `targetName` by slicing it out of `source`.
 * `sourceFile` is the on-disk path (needed to resolve relative imports); pass `null` if unknown
 * (relative imports then decline honestly). Returns `{ ok:false }` for un-isolatable targets —
 * NEVER a fabricated pass.
 */
export function slicePythonFunction(
  source: string,
  targetName: string,
  sourceFile: string | null,
): PySliceResult {
  // Fast path: no imports at all → already self-contained.
  if (!/(?:^|\n)\s*(?:import\s+\w|from\s+[.\w])/.test(source)) {
    return { ok: true, source, inlined: [] };
  }

  let dir: string | null = null;
  try {
    dir = mkdtempSync(join(tmpdir(), 'py-slice-'));
    const scriptFile = join(dir, 'slice.py');
    const jobFile = join(dir, 'job.json');
    writeFileSync(scriptFile, SLICE_SCRIPT, 'utf8');
    writeFileSync(
      jobFile,
      JSON.stringify({ sourceFile: sourceFile ?? '', source, target: targetName }),
      'utf8',
    );
    const stdout = execFileSync(resolvePython(), [scriptFile, jobFile], {
      encoding: 'utf8',
      timeout: 15_000,
      maxBuffer: 16 * 1024 * 1024,
      windowsHide: true,
    });
    const lastLine = stdout.trim().split(/\r?\n/).filter(Boolean).pop() ?? '';
    const parsed = JSON.parse(lastLine) as
      | { ok: true; source: string; inlined: string[] }
      | { ok: false; reason: string };
    if (parsed.ok) return { ok: true, source: parsed.source, inlined: parsed.inlined ?? [] };
    return { ok: false, reason: parsed.reason };
  } catch (e) {
    return { ok: false, reason: `slice extractor failed: ${(e as Error).message}` };
  } finally {
    if (dir) {
      try {
        rmSync(dir, { recursive: true, force: true });
      } catch {
        /* ignore cleanup errors */
      }
    }
  }
}
