/**
 * Cursor adapter for @healthy-ai-code/gate.
 *
 * # Cursor enforcement model (verified against cursor.com/docs/hooks, 2026-06-01)
 *
 * Cursor exposes six lifecycle hooks:
 *   beforeSubmitPrompt   — before the user prompt is submitted; output ignored by Cursor.
 *   beforeShellExecution — before a shell command runs; can return { "continue": false } to block.
 *   beforeMCPExecution   — before an MCP tool call; can return { "continue": false } to block.
 *   beforeReadFile       — before a file is sent to the LLM; can block file access.
 *   afterFileEdit        — INFORMATIONAL ONLY; fired after the edit is already on disk.
 *   stop                 — when the agent task finishes; no blocking.
 *
 * CRITICAL LIMITATION: Cursor has NO pre-edit hook that fires before a file write
 * and can veto it. The `afterFileEdit` hook is explicitly documented as
 * "informational only — you cannot communicate to the user, agent, or stop the agent."
 * (Source: blog.gitbutler.com/cursor-hooks-deep-dive, 2026-06-01;
 *  confirmed: cursor.com/docs/hooks, 2026-06-01)
 *
 * Consequence: the hard deny-before-land model that Claude Code's PreToolUse
 * hook achieves is structurally unavailable in Cursor today.
 *
 * # What this adapter does instead (best-available approach)
 *
 * This adapter implements a three-layer strategy that is the best Cursor can
 * currently enforce:
 *
 *   Layer 1 — Rule injection (.cursor/rules/*.mdc)
 *     Generates a Cursor rules file that instructs the agent to call the gate
 *     before proposing any edit. This is advisory: a sufficiently fast or
 *     cheap model may skip it, and Cursor does not enforce it at the hook level.
 *     The rules file is generated by `writeCursorRulesFile()`.
 *
 *   Layer 2 — Post-edit assessment (afterFileEdit hook)
 *     The adapter exposes `handleAfterFileEditHook()` which reads the
 *     afterFileEdit JSON payload from stdin, re-evaluates the gate on the
 *     current file on disk vs the previous version (if available from git),
 *     and prints a structured warning to stdout if the edit would have been
 *     denied. This warning is visible in the Cursor UI but does NOT block
 *     the edit — it is already on disk.
 *     The generated warning prompts the agent to revert and retry.
 *
 *   Layer 3 — MCP gate tool (beforeMCPExecution, agent-initiated)
 *     When the gate is exposed as an MCP tool and the agent calls it voluntarily,
 *     the beforeMCPExecution hook CAN intercept and block that call — but only
 *     if the agent already chose to call the MCP gate tool. This requires the
 *     rules file (Layer 1) to drive agent compliance.
 *
 * # Comparison with Claude Code adapter
 *
 *   Claude Code PreToolUse → deterministic block BEFORE the edit lands on disk.
 *   Cursor afterFileEdit   → assessment AFTER the edit is already on disk; no block.
 *
 * This difference is not a gap in this implementation — it is a structural
 * limitation of the Cursor hook API as of 2026-06-01. The adapter documents
 * it so operators can make an informed integration decision and are not misled
 * into believing Cursor enforcement is equivalent to Claude Code enforcement.
 */

import * as fs from 'fs';
import * as path from 'path';
import { evaluateGate } from '../evaluate-gate';
import type { GateConfig, GateDecision } from '../gate-types';
import { DEFAULT_FLOOR } from '../gate-types';
import { detectLanguage } from '@healthy-ai-code/core';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Canonical adapter identifier. */
export const ADAPTER_NAME = 'cursor' as const;

/**
 * Human-readable enforcement level for this adapter.
 * "advisory" means the gate informs but CANNOT block an edit before it lands.
 * Contrast with Claude Code's PreToolUse adapter whose level is "enforced".
 */
export const ENFORCEMENT_LEVEL: 'advisory' = 'advisory';

// ---------------------------------------------------------------------------
// Cursor hook JSON shapes (stdin / stdout protocol)
// ---------------------------------------------------------------------------

/**
 * The JSON payload Cursor sends to the `afterFileEdit` hook via stdin.
 * Only fields used by this adapter are typed; the remainder are accepted as
 * unknown to remain forward-compatible with Cursor version changes.
 *
 * Source: cursor.com/docs/hooks (2026-06-01).
 */
export interface CursorAfterFileEditPayload {
  hook_event_name: 'afterFileEdit';
  file_path: string;
  /** Array of { range, text } objects describing the edits applied. */
  edits: CursorEdit[];
  /** Full content of the file after the edit. May be absent in older Cursor versions. */
  file_content_after?: string;
  /** Cursor conversation / generation identifiers (informational). */
  conversation_id?: string;
  generation_id?: string;
  cursor_version?: string;
}

export interface CursorEdit {
  range: {
    start: { line: number; character: number };
    end: { line: number; character: number };
  };
  text: string;
}

/**
 * The JSON object written to stdout by `handleAfterFileEditHook()`.
 * Cursor renders `agentMessage` in the agent context and `userMessage` in the
 * user-facing chat if the hook is configured to surface messages.
 *
 * Note: Cursor's `afterFileEdit` hook is informational — this output will
 * NOT block the edit. The messages are advisory nudges only.
 */
export interface CursorHookOutput {
  /**
   * Always "allow" because afterFileEdit cannot block.
   * Explicit for clarity and to contrast with Claude Code's "deny" path.
   */
  permission: 'allow';
  /** Message visible to the agent (Cursor surfaces this in agent context). */
  agentMessage?: string;
  /** Message shown to the user in the chat UI. */
  userMessage?: string;
  /**
   * Structured gate result for tooling that parses hook stdout as JSON.
   * Not rendered by Cursor itself but useful for test harnesses and CI.
   */
  gateDecision?: GateDecision;
}

/** Re-export GateConfig for callers who want to import from this adapter only. */
export type { GateConfig };

// ---------------------------------------------------------------------------
// Rule file generation (Layer 1 — advisory rules)
// ---------------------------------------------------------------------------

/** Options for `writeCursorRulesFile`. */
export interface WriteCursorRulesFileOptions {
  /** Directory in which to write the `.cursor/rules/` file. Defaults to cwd. */
  projectRoot?: string;
  /** Gate config to embed in the rule description (floor). Optional. */
  gateConfig?: GateConfig;
  /** Overwrite if the file already exists. Default: false. */
  overwrite?: boolean;
}

/** Path segment within the project for the generated rules file. */
export const CURSOR_RULES_RELATIVE_PATH = '.cursor/rules/healthy-ai-code-gate.mdc';

/**
 * Writes (or updates) a Cursor `.mdc` rules file that instructs the agent to
 * call the @healthy-ai-code/gate MCP tool before proposing any file edit.
 *
 * Rules files are advisory in Cursor — the agent is instructed to follow them
 * but the editor does not enforce them at the hook level.
 *
 * @returns The absolute path of the written file.
 */
export function writeCursorRulesFile(options: WriteCursorRulesFileOptions = {}): string {
  const projectRoot = options.projectRoot ?? process.cwd();
  const rulesDir = path.join(projectRoot, '.cursor', 'rules');
  const rulesFile = path.join(rulesDir, 'healthy-ai-code-gate.mdc');

  if (!options.overwrite && fs.existsSync(rulesFile)) {
    return rulesFile;
  }

  fs.mkdirSync(rulesDir, { recursive: true });

  const floor = options.gateConfig?.floor ?? DEFAULT_FLOOR;
  const content = buildRulesFileContent(floor);
  fs.writeFileSync(rulesFile, content, 'utf-8');
  return rulesFile;
}

/** Renders the `.mdc` content for the Cursor rules file. */
function buildRulesFileContent(floor: number): string {
  return `---
description: Healthy AI Code gate — instructs the agent to check health before editing
globs:
  - "**/*.ts"
  - "**/*.tsx"
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.py"
  - "**/*.java"
  - "**/*.go"
  - "**/*.rb"
  - "**/*.rs"
  - "**/*.cs"
  - "**/*.kt"
  - "**/*.scala"
  - "**/*.php"
alwaysApply: false
---

# Healthy AI Code Gate (advisory)

Before proposing any edit to a file covered by this rule, call the
\`code_health_gate\` MCP tool with:
- \`filePath\`: the path of the file you are about to edit
- \`before\`: the current file content
- \`after\`: the content you intend to write

If the tool returns \`verdict: "deny"\`, revise your edit to address the
\`reason\` field before retrying. Do NOT land an edit that the gate denies.

Configured thresholds (from @healthy-ai-code/gate):
- Absolute health floor: ${floor.toFixed(1)} / 10

Note: This rule is advisory. Cursor does not enforce it at the hook level;
compliance depends on the agent following these instructions.
Cursor has no pre-edit hook that can veto a file write before it lands on disk
(source: cursor.com/docs/hooks, 2026-06-01). The afterFileEdit hook used by
this adapter fires AFTER the edit is applied and cannot revert it automatically.
`;
}

// ---------------------------------------------------------------------------
// afterFileEdit hook handler (Layer 2 — post-edit advisory)
// ---------------------------------------------------------------------------

/** Options for `handleAfterFileEditHook`. */
export interface HandleAfterFileEditHookOptions {
  /** Gate configuration. Optional. */
  gateConfig?: GateConfig;
  /**
   * Function that returns the content of the file BEFORE the edit, used for
   * delta evaluation. Typically reads from git HEAD.
   *
   * When not supplied, the gate falls back to evaluating only the after-state
   * (floor check) since there is no prior baseline.
   */
  getBeforeContent?: (filePath: string) => string | null;
  /**
   * Stdin stream. Defaults to process.stdin. Injected for unit testing.
   */
  stdin?: NodeJS.ReadableStream;
  /**
   * Stdout write function. Defaults to process.stdout.write. Injected for testing.
   */
  writeOutput?: (output: string) => void;
}

/**
 * Reads the Cursor `afterFileEdit` hook payload from stdin, evaluates the
 * gate on the file, and writes a JSON advisory to stdout.
 *
 * Because `afterFileEdit` is informational only, the output permission is
 * always `"allow"`. When the gate would have denied, the agentMessage and
 * userMessage fields carry the denial reason as a post-edit warning.
 *
 * @returns The CursorHookOutput that was written to stdout.
 */
export async function handleAfterFileEditHook(
  options: HandleAfterFileEditHookOptions = {},
): Promise<CursorHookOutput> {
  const { gateConfig, getBeforeContent, stdin = process.stdin } = options;
  const writeOutput = options.writeOutput ?? ((s: string) => process.stdout.write(s));

  // Read and parse stdin
  const rawInput = await readStdin(stdin);
  let payload: CursorAfterFileEditPayload;
  try {
    payload = JSON.parse(rawInput) as CursorAfterFileEditPayload;
  } catch {
    const fallback: CursorHookOutput = {
      permission: 'allow',
      agentMessage: 'Healthy AI Code gate: could not parse hook payload (JSON parse error).',
    };
    writeOutput(JSON.stringify(fallback));
    return fallback;
  }

  const { file_path: filePath, file_content_after } = payload;

  // Determine the language; skip unsupported files silently.
  const language = detectLanguage(filePath);
  if (language === 'unsupported') {
    const out: CursorHookOutput = { permission: 'allow' };
    writeOutput(JSON.stringify(out));
    return out;
  }

  // Get after content — prefer the payload field, fall back to reading disk.
  let afterContent: string;
  if (typeof file_content_after === 'string') {
    afterContent = file_content_after;
  } else {
    try {
      afterContent = fs.readFileSync(filePath, 'utf-8');
    } catch {
      // Can't read file; skip evaluation silently.
      const out: CursorHookOutput = { permission: 'allow' };
      writeOutput(JSON.stringify(out));
      return out;
    }
  }

  // Get before content from the injected provider (e.g. git HEAD).
  // When not supplied, pass undefined so evaluateGate treats this as a new file.
  const beforeContent = getBeforeContent ? (getBeforeContent(filePath) ?? undefined) : undefined;

  // Evaluate the gate using the core evaluator (synchronous, <100 ms).
  const decision = evaluateGate(
    {
      filePath,
      language,
      before: beforeContent,
      after: afterContent,
    },
    gateConfig,
  );

  const output = buildHookOutput(decision, filePath);
  writeOutput(JSON.stringify(output));
  return output;
}

// ---------------------------------------------------------------------------
// Decision → hook output mapping
// ---------------------------------------------------------------------------

/**
 * Maps a GateDecision to the CursorHookOutput advisory format.
 *
 * This function encodes the gate verdict into the best available Cursor
 * advisory mechanism. Because afterFileEdit cannot block, all outputs carry
 * `permission: "allow"`. Denied edits become warning messages that the agent
 * is expected to act on by reverting and retrying.
 *
 * This mapping is the core of the Cursor enforcement-limit contract: even a
 * gate `deny` becomes an advisory warning, not a hard block.
 */
export function mapDecisionToHookOutput(decision: GateDecision, filePath: string): CursorHookOutput {
  return buildHookOutput(decision, filePath);
}

function buildHookOutput(decision: GateDecision, filePath: string): CursorHookOutput {
  if (decision.verdict === 'allow') {
    return {
      permission: 'allow',
      gateDecision: decision,
    };
  }

  // Denied — emit a post-edit warning.
  // The edit is already on disk; we cannot revert it automatically.
  // The agent message asks the agent to revert and retry.
  const beforeStr = decision.scoreBefore == null ? 'new file' : decision.scoreBefore.toFixed(2);
  const scoreDelta = decision.scoreAfter - (decision.scoreBefore ?? decision.scoreAfter);
  const agentMessage =
    `[Healthy AI Code gate — POST-EDIT WARNING]\n` +
    `This edit would have been DENIED if the gate had been consulted before writing.\n` +
    `Reason: ${decision.reason}\n` +
    `Score: ${beforeStr} → ${decision.scoreAfter.toFixed(2)} (Δ${scoreDelta.toFixed(2)})\n` +
    `File: ${filePath}\n` +
    `\nPlease revert this edit, address the issue described above, and retry.\n` +
    `(Note: Cursor's afterFileEdit hook cannot block writes. Only the MCP tool\n` +
    ` or a pre-edit agent rule check can prevent unhealthy edits in Cursor.)`;

  const userMessage =
    `Healthy AI Code gate detected an issue with the last edit to ${path.basename(filePath)}.\n` +
    `${decision.reason}\n` +
    `The agent has been asked to revert and retry.`;

  return {
    permission: 'allow',
    agentMessage,
    userMessage,
    gateDecision: decision,
  };
}

// ---------------------------------------------------------------------------
// Adapter metadata (for cross-harness introspection)
// ---------------------------------------------------------------------------

/**
 * Adapter metadata that the gate conformance self-test and any cross-harness
 * orchestration layer can inspect to understand the capabilities of this adapter.
 */
export interface CursorAdapterMetadata {
  /** Canonical adapter identifier. */
  name: typeof ADAPTER_NAME;
  /**
   * Enforcement level relative to Claude Code's PreToolUse hard-deny.
   * "advisory" = the gate informs but cannot block; "enforced" = the gate
   * blocks before the edit lands.
   */
  enforcement: typeof ENFORCEMENT_LEVEL;
  /**
   * Which Cursor hook type the post-edit handler is wired to.
   * afterFileEdit is the only hook that fires on file writes; it is
   * informational only and cannot block or revert an edit.
   */
  hookType: 'afterFileEdit';
  /**
   * Explains why enforcement is advisory rather than enforced.
   * Included so tooling surfacing this metadata can be honest with operators.
   */
  limitationNote: string;
}

/** Returns the metadata object for this adapter. */
export function getCursorAdapterMetadata(): CursorAdapterMetadata {
  return {
    name: ADAPTER_NAME,
    enforcement: ENFORCEMENT_LEVEL,
    hookType: 'afterFileEdit',
    limitationNote:
      'Cursor does not expose a pre-edit hook that can veto a file write before it lands on disk. ' +
      'The afterFileEdit hook is informational only (source: cursor.com/docs/hooks, 2026-06-01). ' +
      'The best available enforcement in Cursor is: (1) a rules file that instructs the agent to ' +
      'call the gate MCP tool before editing, and (2) a post-edit warning that prompts the agent ' +
      'to revert if the gate would have denied. Neither is equivalent to the hard deny that ' +
      "Claude Code's PreToolUse hook provides.",
  };
}

// ---------------------------------------------------------------------------
// Hook configuration helper
// ---------------------------------------------------------------------------

/**
 * Returns the JSON object to merge into a project's `.cursor/hooks.json` to
 * wire the afterFileEdit handler to this adapter's runner script.
 *
 * @param runnerPath - Path to the Node runner script that invokes
 *   `handleAfterFileEditHook`. Example: `node .cursor/hooks/healthy-ai-code-gate.js`
 */
export function buildCursorHooksEntry(runnerPath: string): Record<string, unknown> {
  return {
    afterFileEdit: {
      command: runnerPath,
      timeout: 15000,
    },
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function readStdin(stdin: NodeJS.ReadableStream): Promise<string> {
  return new Promise((resolve, reject) => {
    let data = '';
    stdin.setEncoding('utf-8');
    stdin.on('data', (chunk: string) => { data += chunk; });
    stdin.on('end', () => resolve(data));
    stdin.on('error', reject);
  });
}
